version: '3.0'
services:
  valhalla:
    image: gisops/valhalla:3.0.9 
    ports:
      - "8002:8002"
    volumes:
      - ./custom_files_wmata309/:/custom_files
    environment:
      # The tile_file must be located in the `custom_files` folder.
      # The tile_file has priority and is used when valid.
      # If the tile_file doesn't exist, the url is used instead.
      # Don't blank out tile_url when you use tile_file and vice versa.
      # tile_urls for dc provided but will use one for dc region
      - tile_urls=https://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.pbf
      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
      - min_x=-78.05510 # -> dc region bbox | -180 -> World
      - min_y=38.09884 # -> dc region bbox | -90  -> World
      - max_x=-76.57026 # -> dc region bbox |  180 -> World
      - max_y=39.79251 # -> dc region bbox |  90  -> World
      - use_tiles_ignore_pbf=False
      # Some of these can be toggled on, but they make startup a bit slow, i think unnecessary too
      - force_rebuild=False
      - force_rebuild_elevation=False
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False

